package com.allianz.esb.simpleservice.incident;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-620129
 * 2015-06-18T10:44:04.908+02:00
 * Generated source version: 3.0.4.redhat-620129
 * 
 */
@WebServiceClient(name = "IncidentService", 
                  wsdlLocation = "file:/home/rmarting/Workspaces/fuse-samples/validationSrv/src/main/resources/wsdl/report.wsdl",
                  targetNamespace = "http://incident.simpleservice.esb.allianz.com/") 
public class IncidentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://incident.simpleservice.esb.allianz.com/", "IncidentService");
    public final static QName IncidentServicePort = new QName("http://incident.simpleservice.esb.allianz.com/", "IncidentServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/rmarting/Workspaces/fuse-samples/validationSrv/src/main/resources/wsdl/report.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IncidentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/rmarting/Workspaces/fuse-samples/validationSrv/src/main/resources/wsdl/report.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IncidentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IncidentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IncidentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IncidentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IncidentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IncidentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IncidentServicePortType
     */
    @WebEndpoint(name = "IncidentServicePort")
    public IncidentServicePortType getIncidentServicePort() {
        return super.getPort(IncidentServicePort, IncidentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncidentServicePortType
     */
    @WebEndpoint(name = "IncidentServicePort")
    public IncidentServicePortType getIncidentServicePort(WebServiceFeature... features) {
        return super.getPort(IncidentServicePort, IncidentServicePortType.class, features);
    }

}
