package com.allianz.esb.simpleservice.incident;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-620129
 * 2015-06-18T10:44:04.878+02:00
 * Generated source version: 3.0.4.redhat-620129
 * 
 */
@WebService(targetNamespace = "http://incident.simpleservice.esb.allianz.com/", name = "IncidentServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IncidentServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "reportIncident", targetNamespace = "http://incident.simpleservice.esb.allianz.com/", className = "com.allianz.esb.simpleservice.incident.ReportIncident")
    @WebMethod
    @ResponseWrapper(localName = "reportIncidentResponse", targetNamespace = "http://incident.simpleservice.esb.allianz.com/", className = "com.allianz.esb.simpleservice.incident.ReportIncidentResponse")
    public com.allianz.esb.simpleservice.incident.OutputReportIncident reportIncident(
        @WebParam(name = "arg0", targetNamespace = "")
        com.allianz.esb.simpleservice.incident.InputReportIncident arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "statusIncident", targetNamespace = "http://incident.simpleservice.esb.allianz.com/", className = "com.allianz.esb.simpleservice.incident.StatusIncident")
    @WebMethod
    @ResponseWrapper(localName = "statusIncidentResponse", targetNamespace = "http://incident.simpleservice.esb.allianz.com/", className = "com.allianz.esb.simpleservice.incident.StatusIncidentResponse")
    public com.allianz.esb.simpleservice.incident.OutputStatusIncident statusIncident(
        @WebParam(name = "arg0", targetNamespace = "")
        com.allianz.esb.simpleservice.incident.InputStatusIncident arg0
    );
}
